/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DisplayBook.java
 *
 * Created on Mar 14, 2010, 2:39:28 PM
 */

import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Rohit Aggarwal
 */
public class DisplayBook extends javax.swing.JFrame {

    DisplayBookQuery query_class;
    static String isbn_no;
    private int incr_value = -25;

    /** Creates new form DisplayBook */
    public DisplayBook() {
        initComponents();
        jLabel1.setText(ServerDetails.library_name);
        jLabel1.setSize(jLabel1.getPreferredSize());
        jLabel2.setSize(jLabel2.getPreferredSize());
        jLabel3.setSize(jLabel3.getPreferredSize());
        jLabel4.setSize(jLabel4.getPreferredSize());
        jLabel5.setSize(jLabel5.getPreferredSize());
        jLabel6.setSize(jLabel6.getPreferredSize());
        jLabel7.setSize(jLabel7.getPreferredSize());
        jLabel13.setSize(jLabel13.getPreferredSize());
        jButton3.setSize(jButton3.getPreferredSize());
        if(ServerDetails.database == Database.MSACCESS)
        {
           //query_class = new DisplayBookMSSQL();
        }
        else if(ServerDetails.database == Database.SQLSERVER)
        {
           query_class = new DisplayBookMSSQL();
        }
        else if(ServerDetails.database == Database.MYSQL)
        {
            query_class = new DisplayBookMYSQL();
        }
        else if(ServerDetails.database == Database.POSTGRESQL)
        {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Display Book");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel1.setText("Library Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(275, 20, 161, 29);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel2.setText("ISBN No.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 71, 20);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel3.setText("Title");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 75, 35, 20);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel4.setText("Author");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 145, 53, 20);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel5.setText("Publisher");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(375, 145, 72, 20);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel6.setText("Price");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(375, 110, 38, 20);

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 16)); // NOI18N
        jLabel7.setText("Reference No.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 190, 115, 20);

        jButton3.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton3.setText("Cancel");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(300, 275, 83, 29);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 175, 695, 2);

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel8.setText("Title");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 75, 35, 20);

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel9.setText("ISBN No.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(150, 110, 71, 20);

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel10.setText("Author");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(150, 145, 53, 20);

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel11.setText("Price");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(500, 110, 38, 20);

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel12.setText("Publisher");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(500, 145, 72, 20);

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 1, 16)); // NOI18N
        jLabel13.setText("Status");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(300, 190, 54, 20);

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 225, 0, 0);

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(300, 225, 0, 0);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-700)/2, (screenSize.height-350)/2, 700, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        this.dispose();
        if(ServerDetails.invoker == Invoker.ADMINISTRATOR)
        {
            AdministratorPage admin_page = new AdministratorPage();
            admin_page.show();
        }
        else if(ServerDetails.invoker == Invoker.LIBRARIAN)
        {
            LibrarianPage librarian_page = new LibrarianPage();
            librarian_page.show();
        }
        else
            System.exit(0);
}//GEN-LAST:event_jButton3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try
        {
            ResultSet result_set = query_class.retrieve_book();
            ResultSet result_set_ = query_class.retrieve_books();

            if(result_set.next())
            {
                jLabel8.setText(result_set.getString("Title"));
                jLabel9.setText(result_set.getString("ISBNNo"));
                jLabel10.setText(result_set.getString("Author"));
                jLabel11.setText(result_set.getString("Price"));
                jLabel12.setText(result_set.getString("Publisher"));
                jLabel8.setSize(jLabel8.getPreferredSize());
                jLabel9.setSize(jLabel9.getPreferredSize());
                jLabel10.setSize(jLabel10.getPreferredSize());
                jLabel11.setSize(jLabel11.getPreferredSize());
                jLabel12.setSize(jLabel12.getPreferredSize());

            }

            while(result_set_.next())
            {
                incr_value+=25;

                jLabel14 = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();

                jLabel14.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
                jLabel14.setText(result_set_.getString("ReferenceNo"));
                getContentPane().add(jLabel14);
                jLabel14.setBounds(20, 225 + incr_value, 102, 20);
                jLabel14.setSize(jLabel14.getPreferredSize());

                jLabel15.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
                jLabel15.setText(result_set_.getString("Status"));
                getContentPane().add(jLabel15);
                jLabel15.setBounds(300, 225 + incr_value, 128, 20);
                jLabel15.setSize(jLabel15.getPreferredSize());

                jButton3.setLocation(300, 275 + incr_value);

                java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
                setBounds((screenSize.width-700)/2, (screenSize.height-350 + incr_value)/2, 700, 350 + incr_value);
            }

            this.validate();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null ,"Couldn't connect to the server3.\nCheck the server and restart the Application" + e, "Server Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
