/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditLibraryDetails.java
 *
 * Created on Mar 13, 2010, 11:53:12 PM
 */

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Rohit Aggarwal
 */
public class EditLibraryDetails extends javax.swing.JFrame {

    /** Creates new form EditLibraryDetails */
    public EditLibraryDetails() {
        initComponents();
        jLabel1.setSize(jLabel1.getPreferredSize());
        jLabel2.setSize(jLabel2.getPreferredSize());
        jLabel3.setSize(jLabel3.getPreferredSize());
        jLabel4.setSize(jLabel4.getPreferredSize());
        jLabel5.setSize(jLabel5.getPreferredSize());
        jLabel6.setSize(jLabel6.getPreferredSize());
        jButton1.setSize(jButton1.getPreferredSize());
        jButton2.setSize(jButton2.getPreferredSize());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Library Details");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel1.setText("Library Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 105, 20);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel2.setText("<html>Library Name<br><center>(Abbr.)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 105, 40);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 59, 20);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel4.setText("Website");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(375, 100, 61, 20);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel5.setText("E-Mail ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(375, 140, 74, 20);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel6.setText("Phone Number");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(375, 60, 112, 20);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(145, 15, 500, 26);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(145, 60, 100, 26);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(530, 95, 200, 26);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(530, 135, 200, 26);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(530, 55, 200, 26);

        jTextArea1.setColumns(10);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jTextArea1.setRows(3);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jTextArea1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(145, 110, 200, 100);

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(175, 235, 87, 29);

        jButton2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(475, 235, 83, 29);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-750)/2, (screenSize.height-310)/2, 750, 310);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        if(!(evt.getKeyChar() == '-' || evt.getKeyChar() == '+' || evt.getKeyChar() == '(' || evt.getKeyChar() == ')' || Character.isDigit(evt.getKeyChar())))
            evt.consume();
}//GEN-LAST:event_jTextField5KeyTyped

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(check_data() == true)
        {
            String library_name, address, website, email_id, phone_no, query;
            library_name = jTextField1.getText();
            ServerDetails.library_name = jTextField2.getText();
            address = jTextArea1.getText();
            website = jTextField3.getText();
            email_id = jTextField4.getText();
            phone_no = jTextField5.getText();

            try
            {
                if(ServerDetails.database == Database.MSACCESS)
                {
                }
                else if(ServerDetails.database == Database.SQLSERVER)
                {
                    query = "truncate table LibraryDetail";
                    Statement execute_query = ServerDetails.server_connection.createStatement();
                    execute_query.executeUpdate(query);

                    query = "insert into LibraryDetail (Name, SName, Address, ContactNo, EMailID, Website) values (?,?,?,?,?,?)";
                    PreparedStatement execute_query_ = ServerDetails.server_connection.prepareStatement(query);
                    execute_query_.setString(1, library_name);
                    execute_query_.setString(2, ServerDetails.library_name);
                    execute_query_.setString(3, address);
                    execute_query_.setString(4, phone_no);
                    execute_query_.setString(5, email_id);
                    execute_query_.setString(6, website);
                    execute_query_.executeUpdate();
                    execute_query.close();
                }                 
                else if(ServerDetails.database == Database.MYSQL)
                {
                    query = "truncate table LibraryDetail";
                    Statement execute_query = ServerDetails.server_connection.createStatement();
                    execute_query.executeUpdate(query);

                    query = "insert into LibraryDetail (Name, SName, Address, ContactNo, EMailID, Website) values (?,?,?,?,?,?)";
                    PreparedStatement execute_query_ = ServerDetails.server_connection.prepareStatement(query);
                    execute_query_.setString(1, library_name);
                    execute_query_.setString(2, ServerDetails.library_name);
                    execute_query_.setString(3, address);
                    execute_query_.setString(4, phone_no);
                    execute_query_.setString(5, email_id);
                    execute_query_.setString(6, website);
                    execute_query_.executeUpdate();
                }                 
                else if(ServerDetails.database == Database.POSTGRESQL)
                {
                }

                this.dispose();
                
                if(ServerDetails.invoker == Invoker.ADMINISTRATOR)
                {
                    AdministratorPage admin_page = new AdministratorPage();
                    admin_page.show();
                }
                else if(ServerDetails.invoker == Invoker.LIBRARIAN)
                {
                    LibrarianPage librarian_page = new LibrarianPage();
                    librarian_page.show();
                }
                else
                    System.exit(0);
            } 
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null ,"Couldn't connect to the server.\nCheck the server and restart the Application" +e, "Server Error", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Correct the highlighted items before proceeding", "Incorrect Data", JOptionPane.WARNING_MESSAGE);
}//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        if(ServerDetails.invoker == Invoker.ADMINISTRATOR)
        {
            AdministratorPage admin_page = new AdministratorPage();
            admin_page.show();
        }
        else if(ServerDetails.invoker == Invoker.LIBRARIAN)
        {
            LibrarianPage librarian_page = new LibrarianPage();
            librarian_page.show();
        }
        else
            System.exit(0);
}//GEN-LAST:event_jButton2MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setEditable(true);
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        jTextField2.setEditable(true);
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        // TODO add your handling code here:
        jTextArea1.setEditable(true);
    }//GEN-LAST:event_jTextArea1MouseClicked

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        // TODO add your handling code here:
        jTextField5.setEditable(true);
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        // TODO add your handling code here:
        jTextField3.setEditable(true);
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:
        jTextField4.setEditable(true);
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        jTextField1.setEditable(false);
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        jTextField2.setEditable(false);
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextArea1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea1FocusLost
        // TODO add your handling code here:
        jTextArea1.setEditable(false);
    }//GEN-LAST:event_jTextArea1FocusLost

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
        jTextField5.setEditable(false);
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        jTextField3.setEditable(false);
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:
        jTextField4.setEditable(false);
    }//GEN-LAST:event_jTextField4FocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try
        {
            String query = "select * from LibraryDetail";
            Statement execute_query = ServerDetails.server_connection.createStatement();
            ResultSet result_set = execute_query.executeQuery(query);

            if(result_set.next())
            {
                jTextField1.setText(result_set.getString("Name"));
                jTextField2.setText(result_set.getString("SName"));
                jTextField3.setText(result_set.getString("Website"));
                jTextField4.setText(result_set.getString("EMailID"));
                jTextField5.setText(result_set.getString("ContactNo"));
                jTextArea1.setText(result_set.getString("Address"));
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null ,"Couldn't connect to the server.\nCheck the server and restart the Application", "Server Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowOpened

    private boolean check_data()
    {
        boolean return_value = true;

        if(jTextField1.getText() == null || jTextField1.getText().compareTo("") == 0)
        {
            jLabel1.setText("<html><font color='red'>Library Name");
            return_value = false;
        }
        else
            jLabel1.setText("Library Name");

        if(jTextField2.getText() == null || jTextField2.getText().compareTo("") == 0)
        {
            jLabel2.setText("<html><font color='red'>Library Name<br><center>(Abbr.)");
            return_value = false;
        }
        else
            jLabel2.setText("<html>Library Name<br><center>(Abbr.)");

        if(jTextArea1.getText() == null || jTextArea1.getText().compareTo("") == 0)
        {
            jLabel3.setText("<html><font color='red'>Address");
            return_value = false;
        }
        else
            jLabel3.setText("Address");

        if(jTextField3.getText() == null || jTextField3.getText().compareTo("") == 0)
        {
            jLabel4.setText("<html><font color='red'>Website");
            return_value = false;
        }
        else
            jLabel4.setText("Website");

        if(jTextField4.getText() == null || jTextField4.getText().compareTo("") == 0)
        {
            jLabel5.setText("<html><font color='red'>E-Mail ID");
            return_value = false;
        }
        else
            jLabel5.setText("E-Mail ID");

        if(jTextField5.getText() == null || jTextField5.getText().compareTo("") == 0)
        {
            jLabel5.setText("<html><font color='red'>Phone No.");
            return_value = false;
        }
        else
            jLabel5.setText("Phoen No.");

        return(return_value);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditLibraryDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
