/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Leave.java
 *
 * Created on Feb 28, 2010, 12:07:52 AM
 */

import javax.swing.JOptionPane;
import java.util.Calendar;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;

/**
 *
 * @author Rohit Aggarwal
 */
public class Leave extends javax.swing.JFrame {

    LeaveQuery query_class;
    static String employee_code, leave_details;
    static Calendar leave_date = Calendar.getInstance();

    /** Creates new form Leave */
    public Leave() {
        initComponents();
        jLabel1.setText(ServerDetails.library_name);
        jLabel1.setSize(jLabel1.getPreferredSize());
        jLabel2.setSize(jLabel2.getPreferredSize());
        jLabel3.setSize(jLabel3.getPreferredSize());
        jLabel4.setSize(jLabel4.getPreferredSize());
        jButton1.setSize(jButton1.getPreferredSize());
        jButton2.setSize(jButton2.getPreferredSize());
        if(ServerDetails.database == Database.MSACCESS)
        {
           //query_class = new LeaveMSSQL();
        }
        else if(ServerDetails.database == Database.SQLSERVER)
        {
           query_class = new LeaveMSSQL();
        }
        else if(ServerDetails.database == Database.MYSQL)
        {
           //query_class = new LeaveMYSQL();
        }
        else if(ServerDetails.database == Database.POSTGRESQL)
        {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Leave");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 24));
        jLabel1.setText("Library Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(115, 20, 161, 29);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel2.setText("Employee ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 75, 96, 20);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel3.setText("Leave Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 84, 20);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel4.setText("Leave Details");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 145, 101, 20);

        jTextField1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 70, 150, 26);

        jTextArea1.setColumns(10);
        jTextArea1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jTextArea1.setRows(3);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 140, 200, 100);

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 255, 87, 29);

        jButton2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 255, 83, 29);

        jComboBox1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(160, 105, 49, 26);

        jComboBox2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(215, 105, 110, 26);

        jComboBox3.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(330, 105, 35, 26);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-425)/2, (screenSize.height-330)/2, 425, 330);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(check_data() == true)
        {
            employee_code = jTextField1.getText();
            leave_date.clear();
            leave_date.set(Integer.parseInt(jComboBox3.getSelectedItem().toString()), jComboBox2.getSelectedIndex(), Integer.parseInt(jComboBox1.getSelectedItem().toString()));
            leave_details = jTextArea1.getText();
            if(query_class.check_employee() == true)
            {
                query_class.insert_values();
                this.dispose();
            }
            else
                JOptionPane.showMessageDialog(this, "Employee:" + employee_code + " doesn't exists in the database.", "Invalid Employee", JOptionPane.WARNING_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(this, "Correct the highlighted items before proceeding", "Incorrect Data", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        if(ServerDetails.invoker == Invoker.ADMINISTRATOR)
        {
            AdministratorPage admin_page = new AdministratorPage();
            admin_page.show();
        }
        else if(ServerDetails.invoker == Invoker.LIBRARIAN)
        {
            LibrarianPage librarian_page = new LibrarianPage();
            librarian_page.show();
        }
        else
            System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Calendar now = Calendar.getInstance();
        now.setTime(new java.util.Date());
        for(int i = now.get(Calendar.YEAR); i >= now.get(Calendar.YEAR)-2; i--)
            jComboBox3.addItem(i);
        jComboBox3.setSize(jComboBox3.getPreferredSize());
    }//GEN-LAST:event_formWindowOpened

    private boolean check_data()
    {
        boolean return_value=true;

        if(jTextField1.getText() == null || jTextField1.getText().compareTo("") == 0)
        {
            jLabel2.setText("<html><font color='red'>Employee ID");
            return_value = false;
        }
        else
            jLabel2.setText("Employee ID");

        if(jTextArea1.getText() == null || jTextArea1.getText().compareTo("") == 0)
        {
            jLabel4.setText("<html><font color='red'>Leave Details");
            return_value = false;
        }
        else
            jLabel4.setText("Leave Details");

        if(check_date() == false)
        {
            jLabel3.setText("<html><font color='red'>Leave Date");
            return_value = false;
        }
        else
            jLabel3.setText("Leave Date");

        return(return_value);
    }

    private boolean check_date()
    {
        boolean return_value = true;
        String date = (jComboBox2.getSelectedIndex()+1) + "/" + jComboBox1.getSelectedItem().toString() + "/" + jComboBox3.getSelectedItem().toString();

        try
        {
            DateFormat date_format = DateFormat.getDateInstance(DateFormat.SHORT);
            date_format.setLenient(false);
            Date temp_date = date_format.parse(date);
        }
        catch(ParseException e)
        {
            return_value = false;
        }

        return(return_value);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
