/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CollegeDetails.java
 *
 * Created on Dec 26, 2009, 12:25:46 AM
 */

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Rohit Aggarwal
 */
public class LibraryDetails extends javax.swing.JFrame {

    
    /** Creates new form CollegeDetails */
    public LibraryDetails() {
        initComponents();
        jLabel1.setSize(jLabel1.getPreferredSize());
        jLabel2.setSize(jLabel2.getPreferredSize());
        jLabel3.setSize(jLabel3.getPreferredSize());
        jLabel4.setSize(jLabel4.getPreferredSize());
        jLabel5.setSize(jLabel5.getPreferredSize());
        jLabel6.setSize(jLabel6.getPreferredSize());
        jButton1.setSize(jButton1.getPreferredSize());
        jButton2.setSize(jButton2.getPreferredSize());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Details");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel1.setText("Library Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 105, 20);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel2.setText("<html>Library Name<br><center>(Abbr.)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 105, 40);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 59, 20);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel4.setText("Website");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(375, 100, 61, 20);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel5.setText("E-Mail ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(375, 140, 74, 20);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel6.setText("Phone Number");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(375, 60, 112, 20);

        jTextField1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(145, 15, 500, 26);

        jTextField2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(145, 60, 100, 26);

        jTextField3.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(530, 95, 200, 26);

        jTextField4.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(530, 135, 200, 26);

        jTextField5.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(530, 55, 200, 26);

        jTextArea1.setColumns(10);
        jTextArea1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jTextArea1.setRows(3);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(145, 110, 200, 100);

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton1.setText("Continue");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(175, 235, 101, 29);

        jButton2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(475, 235, 83, 29);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-750)/2, (screenSize.height-310)/2, 750, 310);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(check_data() == true)
        {
            String college_name, address, website, email_id, phone_no, query;
            college_name = jTextField1.getText();
            ServerDetails.library_name = jTextField2.getText();
            address = jTextArea1.getText();
            website = jTextField3.getText();
            email_id = jTextField4.getText();
            phone_no = jTextField5.getText();

            try
            {
                if(ServerDetails.database == Database.SQLSERVER)
                {
                    query = "insert into LibraryDetail (Name, SName, Address, ContactNo, EMailID, Website) values (?,?,?,?,?,?)";
                    PreparedStatement execute_query = ServerDetails.server_connection.prepareStatement(query);
                    execute_query.setString(1, college_name);
                    execute_query.setString(2, ServerDetails.library_name);
                    execute_query.setString(3, address);
                    execute_query.setString(4, phone_no);
                    execute_query.setString(5, email_id);
                    execute_query.setString(6, website);
                    execute_query.executeUpdate();
                    execute_query.close();
                }
                else if(ServerDetails.database == Database.MYSQL)
                {
                    query = "insert into LibraryDetail (Name, SName, Address, ContactNo, EMailID, Website) values (?,?,?,?,?,?)";
                    PreparedStatement execute_query = ServerDetails.server_connection.prepareStatement(query);
                    execute_query.setString(1, college_name);
                    execute_query.setString(2, ServerDetails.library_name);
                    execute_query.setString(3, address);
                    execute_query.setString(4, phone_no);
                    execute_query.setString(5, email_id);
                    execute_query.setString(6, website);
                    execute_query.executeUpdate();
                    execute_query.close();
                }
                else if(ServerDetails.database == Database.POSTGRESQL)
                {
                }               
                this.dispose();
                AdministratorPage admin_page = new AdministratorPage();
                admin_page.show();
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null ,"Couldn't connect to the server.\nCheck the server and restart the Application", "Server Error", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Correct the highlighted items before proceeding", "Incorrect Data", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        AdministratorPage admin_page = new AdministratorPage();
        admin_page.show();        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        if(!(evt.getKeyChar() == '-' || evt.getKeyChar() == '+' || evt.getKeyChar() == '(' || evt.getKeyChar() == ')' || Character.isDigit(evt.getKeyChar())))
            evt.consume();
    }//GEN-LAST:event_jTextField5KeyTyped

    private boolean check_data()
    {
        boolean return_value = true;
        
        if(jTextField1.getText() == null || jTextField1.getText().compareTo("") == 0)
        {
            jLabel1.setText("<html><font color='red'>Library Name");
            return_value = false;
        }
        else
            jLabel1.setText("Library Name");

        if(jTextField2.getText() == null || jTextField2.getText().compareTo("") == 0)
        {
            jLabel2.setText("<html><font color='red'>Library Name<br><center>(Abbr.)");
            return_value = false;
        }
        else
            jLabel2.setText("<html>Library Name<br><center>(Abbr.)");

        if(jTextArea1.getText() == null || jTextArea1.getText().compareTo("") == 0)
        {
            jLabel3.setText("<html><font color='red'>Address");
            return_value = false;
        }
        else
            jLabel3.setText("Address");

        if(jTextField3.getText() == null || jTextField3.getText().compareTo("") == 0)
        {
            jLabel4.setText("<html><font color='red'>Website");
            return_value = false;
        }
        else
            jLabel4.setText("Website");

        if(jTextField4.getText() == null || jTextField4.getText().compareTo("") == 0)
        {
            jLabel5.setText("<html><font color='red'>E-Mail ID");
            return_value = false;
        }
        else
            jLabel5.setText("E-Mail ID");

        if(jTextField5.getText() == null || jTextField5.getText().compareTo("") == 0)
        {
            jLabel6.setText("<html><font color='red'>Phone No.");
            return_value = false;
        }
        else
            jLabel6.setText("Phone No.");
                
        return(return_value);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
