/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;

/*
 * MemberPage.java
 *
 * Created on Mar 13, 2010, 4:04:02 PM
 */

/**
 *
 * @author Rohit Aggarwal
 */
public class MemberPage extends javax.swing.JFrame {

    static String isbn_no;
    MemberPageQuery query_class;

    /** Creates new form MemberPage */
    public MemberPage() {
        initComponents();
        jLabel1.setSize(jLabel1.getPreferredSize());
        jLabel2.setSize(jLabel2.getPreferredSize());
        jLabel5.setSize(jLabel5.getPreferredSize());
        jLabel6.setSize(jLabel6.getPreferredSize());
        jLabel7.setSize(jLabel7.getPreferredSize());
        jButton1.setSize(jButton1.getPreferredSize());
        if(ServerDetails.database == Database.MSACCESS)
        {
           //query_class = new AdministratorPageAcess;
        }
        else if(ServerDetails.database == Database.SQLSERVER)
        {
           query_class = new MemberPageMSSQL();
        }
        else if(ServerDetails.database == Database.MYSQL)
        {
            query_class = new MemberPageMYSQL();
        }
        else if(ServerDetails.database == Database.POSTGRESQL)
        {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu6 = new javax.swing.JPopupMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPopupMenu6.setInvoker(jLabel5);

        jMenuItem16.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jMenuItem16.setText("Display Book");
        jMenuItem16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem16MousePressed(evt);
            }
        });
        jPopupMenu6.add(jMenuItem16);

        jMenuItem21.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jMenuItem21.setText("Search Book");
        jMenuItem21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem21MousePressed(evt);
            }
        });
        jPopupMenu6.add(jMenuItem21);

        jPopupMenu5.setInvoker(jLabel6);

        jMenuItem8.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jMenuItem8.setText("Personal Details");
        jMenuItem8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem8MousePressed(evt);
            }
        });
        jPopupMenu5.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jMenuItem9.setText("Change Password");
        jMenuItem9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem9MousePressed(evt);
            }
        });
        jPopupMenu5.add(jMenuItem9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Member Page");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 18));
        jLabel1.setText("Welcome,");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 85, 22);

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton1.setText("Exit Application");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(125, 195, 153, 29);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel2.setText("<html><u>Library Details");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 75, 113, 20);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel6.setText("<html><u>Edit Details");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 125, 88, 20);

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel7.setText("<html><u>Logout");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 150, 52, 20);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel5.setText("<html><u>Books");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 100, 44, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-375)/2, (screenSize.height-275)/2, 375, 275);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_jButton1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        DisplayLibraryDetails display_library = new DisplayLibraryDetails();
        display_library.show();
}//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        jPopupMenu5.show(jLabel6, 80, 10);
}//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Login login = new Login();
        login.show();
}//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        if(query_class.check_book() == false)
        {
            jMenuItem16.hide();
            jMenuItem16.disable();
            jMenuItem21.hide();
            jMenuItem21.disable();
        }
        jPopupMenu6.show(jLabel5, 60, 10);
}//GEN-LAST:event_jLabel5MouseClicked

    private void jMenuItem16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem16MousePressed
        // TODO add your handling code here:
        jPopupMenu6.setVisible(false);
        this.dispose();
        do
        {
            DisplayBook.isbn_no = JOptionPane.showInputDialog(this, "Enter the ISBN Number of the Book: ", "Enter ISBN No.", JOptionPane.QUESTION_MESSAGE);
            if(DisplayBook.isbn_no == null)
            {
                MemberPage member_page = new MemberPage();
                member_page.show();
                break;
            }
            else if(DisplayBook.isbn_no.length() != 0)
            {
                isbn_no = DisplayBook.isbn_no;
                if(query_class.check_isbn_book() == true)
                {
                    DisplayBook display_book = new DisplayBook();
                    display_book.show();
                    break;
                }
                else
                {
                    int answer = JOptionPane.showConfirmDialog(this, "Book: " + DisplayBook.isbn_no + " doesn't exists in the database.\nWant to try Again?" , "Invalid ISBN No.", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                    if(answer == JOptionPane.NO_OPTION)
                    {
                        MemberPage member_page = new MemberPage();
                        member_page.show();
                        break;
                    }
                }
            }
        }while(true);
    }//GEN-LAST:event_jMenuItem16MousePressed

    private void jMenuItem21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem21MousePressed
        // TODO add your handling code here:
        this.dispose();
        SearchBook search_book = new SearchBook();
        search_book.show();
    }//GEN-LAST:event_jMenuItem21MousePressed

    private void jMenuItem8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem8MousePressed
        // TODO add your handling code here:
        this.dispose();
        EditMemberDetails.member_id = query_class.retrieve_member_id();
        EditMemberDetails edit_member = new EditMemberDetails();
        edit_member.show();
    }//GEN-LAST:event_jMenuItem8MousePressed

    private void jMenuItem9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem9MousePressed
        // TODO add your handling code here:
        this.dispose();
        ChangePassword change_password = new ChangePassword();
        change_password.show();
    }//GEN-LAST:event_jMenuItem9MousePressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JPopupMenu jPopupMenu6;
    // End of variables declaration//GEN-END:variables

}
