/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewBook.java
 *
 * Created on Feb 28, 2010, 12:44:56 PM
 */

import javax.swing.*;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author Rohit Aggarwal
 */
public class NewBook extends javax.swing.JFrame {

    NewBookQuery query_class;
    static String title, isbn_no, author, publisher;
    static long price;
    private int incr_value, total_books;
    static int book_count;
    static List<JTextField> reference_no = new ArrayList<JTextField>();

    /** Creates new form NewBook */
    public NewBook() {
        initComponents();
        book_count = 1;
        total_books = 1;
        reference_no.add(jTextField6);
        incr_value = 0;
        jLabel1.setText(ServerDetails.library_name);
        jLabel1.setSize(jLabel1.getPreferredSize());
        jLabel2.setSize(jLabel2.getPreferredSize());
        jLabel3.setSize(jLabel3.getPreferredSize());
        jLabel4.setSize(jLabel4.getPreferredSize());
        jLabel5.setSize(jLabel5.getPreferredSize());
        jLabel6.setSize(jLabel6.getPreferredSize());
        jLabel7.setSize(jLabel7.getPreferredSize());
        jButton1.setSize(jButton1.getPreferredSize());
        jButton2.setSize(jButton2.getPreferredSize());
        jButton3.setSize(jButton3.getPreferredSize());
        if(ServerDetails.database == Database.MSACCESS)
        {
           //query_class = new NewBookMSSQL();
        }
        else if(ServerDetails.database == Database.SQLSERVER)
        {
           query_class = new NewBookMSSQL();
        }
        else if(ServerDetails.database == Database.MYSQL)
        {
            query_class = new NewBookMYSQL();
        }
        else if(ServerDetails.database == Database.POSTGRESQL)
        {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Book");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 24));
        jLabel1.setText("Library Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(275, 20, 161, 29);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel2.setText("ISBN No.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 71, 20);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel3.setText("Title");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 75, 35, 20);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel4.setText("Author");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 145, 53, 20);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel5.setText("Publisher");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(375, 145, 72, 20);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel6.setText("Price");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(375, 110, 38, 20);

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel7.setText("Reference No.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 190, 102, 20);

        jTextField1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(125, 105, 200, 26);

        jTextField2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(125, 70, 500, 26);

        jTextField3.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(125, 140, 200, 26);

        jTextField4.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(475, 140, 200, 26);

        jTextField5.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(475, 105, 125, 26);

        jTextField6.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(250, 190, 200, 26);

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton1.setText("Add");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(575, 190, 63, 29);

        jButton2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton2.setText("Submit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 250, 87, 29);

        jButton3.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton3.setText("Cancel");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 250, 83, 29);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 175, 695, 2);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-700)/2, (screenSize.height-325)/2, 700, 325);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        if(!(Character.isDigit(evt.getKeyChar())))
            evt.consume();
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        incr_value+=35;
        book_count++;
        total_books++;

        jTextField6 = new javax.swing.JTextField();

        jTextField6.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(250, 190 + incr_value, 200, 26);
        reference_no.add(jTextField6);

        jButton1.setLocation(575, 190 + incr_value);
        jButton2.setLocation(150, 250 + incr_value);
        jButton3.setLocation(450, 250 + incr_value);
        
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-700)/2, (screenSize.height-(325 + incr_value))/2, 700, 325 + incr_value);

        this.validate();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if(check_data() == true)
        {
            isbn_no = jTextField1.getText();
            author = jTextField3.getText();
            publisher = jTextField4.getText();;
            price = Integer.parseInt(jTextField5.getText());
            title = jTextField2.getText();

            if(query_class.check_book() == false)
            {
                query_class.insert_values();
                reference_no.removeAll(reference_no);
                this.dispose();
                if(ServerDetails.invoker == Invoker.ADMINISTRATOR)
                {
                    AdministratorPage admin_page = new AdministratorPage();
                    admin_page.show();
                }
                else if(ServerDetails.invoker == Invoker.LIBRARIAN)
                {
                    LibrarianPage librarian_page = new LibrarianPage();
                    librarian_page.show();
                }
                else if(ServerDetails.invoker == Invoker.EMPLOYEE)
                {
                    EmployeePage employee_page = new EmployeePage();
                    employee_page.show();
                }
                else
                    System.exit(0);
            }
            else
                JOptionPane.showMessageDialog(this, "The Book:" + isbn_no + " already exists in the database.", "Duplicate Book", JOptionPane.WARNING_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(this, "Correct the highlighted items before proceeding", "Incorrect Data", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        this.dispose();
        reference_no.removeAll(reference_no);
        if(ServerDetails.invoker == Invoker.ADMINISTRATOR)
        {
            AdministratorPage admin_page = new AdministratorPage();
            admin_page.show();
        }
        else if(ServerDetails.invoker == Invoker.LIBRARIAN)
        {
            LibrarianPage librarian_page = new LibrarianPage();
            librarian_page.show();
        }
        else if(ServerDetails.invoker == Invoker.EMPLOYEE)
        {
            EmployeePage employee_page = new EmployeePage();
            employee_page.show();
        }
        else
            System.exit(0);
    }//GEN-LAST:event_jButton3MouseClicked

    private boolean check_data()
    {
        boolean return_value=true;
        JTextField temp_reference_no;
        
        if(jTextField1.getText() == null || jTextField1.getText().compareTo("") == 0)
        {
            jLabel2.setText("<html><font color='red'>ISBN No.");
            return_value = false;
        }
        else
            jLabel2.setText("ISBN No.");

        if(jTextField2.getText() == null || jTextField2.getText().compareTo("") == 0)
        {
            jLabel3.setText("<html><font color='red'>Title");
            return_value = false;
        }
        else
            jLabel3.setText("Title");

        if(jTextField3.getText() == null || jTextField3.getText().compareTo("") == 0)
        {
            jLabel4.setText("<html><font color='red'>Author");
            return_value = false;
        }
        else
            jLabel4.setText("Author");

        if(jTextField4.getText() == null || jTextField4.getText().compareTo("") == 0)
        {
            jLabel5.setText("<html><font color='red'>Publisher");
            return_value = false;
        }
        else
            jLabel5.setText("Publisher");

        if(jTextField5.getText() == null || jTextField5.getText().compareTo("") == 0)
        {
            jLabel6.setText("<html><font color='red'>Price");
            return_value = false;
        }
        else
            jLabel6.setText("Price");

        for(int i = 0; i < book_count; i++)
        {
            temp_reference_no = reference_no.get(i);
            total_books--;
            if(temp_reference_no.getText() == null || temp_reference_no.getText().compareTo("") == 0)
            {
                temp_reference_no = reference_no.remove(i);
                incr_value-=35;

                jButton2.setLocation(150, 250 + incr_value);
                jButton3.setLocation(450, 250 + incr_value);
                java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
                setBounds((screenSize.width-700)/2, (screenSize.height-(325+incr_value))/2, 700, 325+incr_value);

                book_count--;
                i--;
                this.remove(temp_reference_no);
                
                for(int j=1; j <= total_books; j++)
                {
                    temp_reference_no = reference_no.get(j+i);
                    double y = temp_reference_no.getLocation().getY();
                    temp_reference_no.setLocation(250, (int)(y-35));
                }
                jButton1.setBounds(575, 190 + incr_value, 65, 29);
                this.validate();
                return_value = false;
            }
        }
        total_books = book_count;

        return(return_value);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
