/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewMembership.java
 *
 * Created on Mar 14, 2010, 12:04:41 AM
 */

import javax.swing.JOptionPane;

/**
 *
 * @author Rohit Aggarwal
 */
public class NewMembership extends javax.swing.JFrame {

    NewMembershipQuery query_class;
    static String membership;
    static int book_limit;

    /** Creates new form NewMembership */
    public NewMembership() {
        initComponents();
        jLabel1.setText(ServerDetails.library_name);
        jLabel1.setSize(jLabel1.getPreferredSize());
        jLabel2.setSize(jLabel2.getPreferredSize());
        jLabel3.setSize(jLabel3.getPreferredSize());
        jButton1.setSize(jButton1.getPreferredSize());
        jButton2.setSize(jButton2.getPreferredSize());
        if(ServerDetails.database == Database.MSACCESS)
        {
           //query_class = new NewMembershipMSSQL();
        }
        else if(ServerDetails.database == Database.SQLSERVER)
        {
           query_class = new NewMembershipMSSQL();
        }
        else if(ServerDetails.database == Database.MYSQL)
        {
           query_class = new NewMembershipMYSQL();
        }
        else if(ServerDetails.database == Database.POSTGRESQL)
        {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Membership");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel1.setText("Library Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(75, 20, 161, 29);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel2.setText("Membership");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 92, 20);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel3.setText("Book Limit");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 82, 20);

        jTextField1.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 75, 150, 26);

        jTextField2.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 115, 100, 26);

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 165, 87, 29);

        jButton2.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 165, 83, 29);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-325)/2, (screenSize.height-240)/2, 325, 240);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        if(!(Character.isDigit(evt.getKeyChar())))
            evt.consume();
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(check_data() == true)
        {
            membership = jTextField1.getText();
            book_limit = Integer.parseInt(jTextField2.getText());
            if(query_class.check_membership())
            {
                query_class.insert_values();
                this.dispose();
                if(ServerDetails.invoker == Invoker.ADMINISTRATOR)
                {
                    AdministratorPage admin_page = new AdministratorPage();
                    admin_page.show();
                }
                else if(ServerDetails.invoker == Invoker.LIBRARIAN)
                {
                    LibrarianPage librarian_page = new LibrarianPage();
                    librarian_page.show();
                }
                else
                    System.exit(0);
            }
            else
                JOptionPane.showMessageDialog(this, "Membership:" + membership + " is already present in the database.", "Duplicate Membership", JOptionPane.WARNING_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(this, "Correct the highlighted items before proceeding", "Incorrect Data", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        if(ServerDetails.invoker == Invoker.ADMINISTRATOR)
        {
            AdministratorPage admin_page = new AdministratorPage();
            admin_page.show();
        }
        else if(ServerDetails.invoker == Invoker.LIBRARIAN)
        {
            LibrarianPage librarian_page = new LibrarianPage();
            librarian_page.show();
        }
        else
            System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private boolean check_data()
    {
        boolean return_value=true;

        if(jTextField1.getText() == null || jTextField1.getText().compareTo("") == 0)
        {
            jLabel2.setText("<html><font color='red'>Membership");
            return_value = false;
        }
        else
            jLabel2.setText("Membership");

        if(jTextField2.getText() == null || jTextField2.getText().compareTo("") == 0)
        {
            jLabel3.setText("<html><font color='red'>Book Limit");
            return_value = false;
        }
        else
            jLabel3.setText("Book Limit");

        return(return_value);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMembership().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
