/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewUser.java
 *
 * Created on Jan 1, 2010, 9:10:35 PM
 */

import javax.swing.JOptionPane;

/**
 *
 * @author Rohit Aggarwal
 */
public class NewUser extends javax.swing.JFrame {

    NewUserQuery query_class;
    static String user_name, password, confirm_password, unique_no;

    /** Creates new form NewUser */
    public NewUser() {
        initComponents();
        jLabel1.setText(ServerDetails.library_name);
        jLabel1.setSize(jLabel1.getPreferredSize());
        jLabel3.setSize(jLabel3.getPreferredSize());
        jLabel5.setSize(jLabel5.getPreferredSize());
        jLabel6.setSize(jLabel6.getPreferredSize());
        jLabel7.setSize(jLabel7.getPreferredSize());
        jButton1.setSize(jButton1.getPreferredSize());
        jButton2.setSize(jButton2.getPreferredSize());
        if(ServerDetails.database == Database.MSACCESS)
        {
           //query_class = new NewUserMSSQL();
        }
        else if(ServerDetails.database == Database.SQLSERVER)
        {
           query_class = new NewUserMSSQL();
        }
        else if(ServerDetails.database == Database.MYSQL)
        {
            query_class = new NewUserMYSQL();
        }
        else if(ServerDetails.database == Database.POSTGRESQL)
        {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New User");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 24));
        jLabel1.setText("Library Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 161, 29);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel3.setText("Member ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 75, 84, 20);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel5.setText("User Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 110, 83, 20);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 145, 69, 20);

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton1.setText("Create");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 225, 83, 29);

        jButton2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 225, 83, 29);

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel7.setText("Confirm Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 180, 134, 20);

        jTextField1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(190, 70, 200, 26);

        jTextField2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(190, 105, 200, 26);

        jPasswordField1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(190, 140, 200, 26);

        jPasswordField2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(190, 175, 200, 26);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-425)/2, (screenSize.height-300)/2, 425, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(check_data() == true)
        {
            unique_no = jTextField1.getText();
            user_name = jTextField2.getText();
            password = jPasswordField1.getText();
            confirm_password = jPasswordField2.getText();
            
            if(!(query_class.check_unique_id_exists()))
                JOptionPane.showMessageDialog(this, unique_no + " doesn't exists in the database.", "Invalid Identification", JOptionPane.WARNING_MESSAGE);
            else
            {
                if(!(query_class.check_unique_id()))
                {
                    if(!(query_class.check_user_name()))
                    {
                        query_class.insert_values();
                        JOptionPane.showMessageDialog(this, "User with User Name:" + user_name + " has been created.", "User Created", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                        Login login = new Login();
                        login.show();
                    }
                    else
                        JOptionPane.showMessageDialog(this, "User Name:" + user_name + " already exists in the database.", "Incorrect User Name", JOptionPane.WARNING_MESSAGE);                        
                }
                else
                    JOptionPane.showMessageDialog(this, "User:" + unique_no + " already has a User Login ID", "Duplicate Entry", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
           JOptionPane.showMessageDialog(this, "Correct the highlighted items before proceeding", "Incorrect Data", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Login login = new Login();
        login.show();
    }//GEN-LAST:event_jButton2MouseClicked

    private boolean check_data()
    {
        boolean return_value= true;

        if(jTextField1.getText() == null || jTextField1.getText().compareTo("") == 0)
        {
            jLabel3.setText("<html><font color='red'>Member ID");
            return_value = false;
        }
        else
        {
            jLabel3.setText("Member ID");
        }

        if(jTextField2.getText() == null || jTextField2.getText().compareTo("") == 0)
        {
            jLabel5.setText("<html><font color='red'>User Name");
            return_value = false;
        }
        else
            jLabel5.setText("User Name");

        if(jPasswordField1.getText() == null || jPasswordField1.getText().compareTo("") == 0)
        {
            jLabel6.setText("<html><font color='red'>Password");
            return_value = false;
        }
        else
            jLabel6.setText("<html>Password");

        if(jPasswordField2.getText() == null || jPasswordField2.getText().compareTo("") == 0)
        {
            jLabel7.setText("<html><font color='red'>Confirm Password");
            return_value = false;
        }
        else
            jLabel7.setText("<html>Confirm Password");

        if(jPasswordField2.getText().compareTo(jPasswordField1.getText()) != 0)
        {
            jLabel6.setText("<html><font color='red'>Password");
            jLabel7.setText("<html><font color='red'>Confirm Password");
            return_value = false;
        }
        else if(jPasswordField2.getText().compareTo(jPasswordField1.getText()) == 0 && (jPasswordField1.getText() == null || jPasswordField1.getText().compareTo("") != 0 && jPasswordField2.getText() == null || jPasswordField2.getText().compareTo("") != 0))
        {
            jLabel6.setText("Password");
            jLabel7.setText("Confirm Password");
        }

        return(return_value);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
