/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudentReturn.java
 *
 * Created on Feb 28, 2010, 3:23:37 PM
 */

import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.text.DateFormat;

/**
 *
 * @author Rohit Aggarwal
 */
public class Return extends javax.swing.JFrame {

    public static String member_id, reference_no;
    static int fine;
    static Calendar date_of_issue = Calendar.getInstance(), date_of_return = Calendar.getInstance();
    Date return_date;
    ReturnQuery query_class;
    
    /** Creates new form StudentReturn */
    public Return() {
        initComponents();
        jLabel1.setText(ServerDetails.library_name);
        jLabel1.setSize(jLabel1.getPreferredSize());
        jLabel2.setSize(jLabel2.getPreferredSize());
        jLabel3.setSize(jLabel3.getPreferredSize());
        jLabel4.setSize(jLabel4.getPreferredSize());
        jLabel5.setSize(jLabel5.getPreferredSize());
        jLabel6.setSize(jLabel6.getPreferredSize());
        jButton1.setSize(jButton1.getPreferredSize());
        jButton2.setSize(jButton2.getPreferredSize());
        if(ServerDetails.database == Database.MSACCESS)
        {
           //query_class = new ReturnMSSQL();
        }
        else if(ServerDetails.database == Database.SQLSERVER)
        {
           query_class = new ReturnMSSQL();
        }
        else if(ServerDetails.database == Database.MYSQL)
        {
            query_class = new ReturnMYSQL();
        }
        else if(ServerDetails.database == Database.POSTGRESQL)
        {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Return");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel1.setText("Library Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 20, 161, 29);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jLabel2.setText("Member ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 75, 84, 20);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel3.setText("Member ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 75, 84, 20);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel4.setText("Reference No.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 115, 102, 20);

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel5.setText("Date of Issue");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 155, 95, 20);

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel6.setText("Date of Return");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 195, 109, 20);

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jButton1.setText("Return");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 275, 85, 29);

        jButton2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 275, 83, 29);

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel10.setText("Reference No.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(150, 115, 102, 20);

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel11.setText("Date of Issue");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(150, 155, 95, 20);

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel12.setText("Date of Return");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(150, 195, 109, 20);

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel13.setText("Fine");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(150, 235, 34, 20);

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel14.setText("Fine");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 235, 34, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-375)/2, (screenSize.height-350)/2, 375, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        fine = calculate_fine();
        query_class.insert_values();
        this.dispose();
        if(ServerDetails.invoker == Invoker.ADMINISTRATOR)
        {
            AdministratorPage admin_page = new AdministratorPage();
            admin_page.show();
        }
        else if(ServerDetails.invoker == Invoker.LIBRARIAN)
        {
            LibrarianPage librarian_page = new LibrarianPage();
            librarian_page.show();
        }
        else if(ServerDetails.invoker == Invoker.EMPLOYEE)
        {
            EmployeePage employee_page = new EmployeePage();
            employee_page.show();
        }
        else
            System.exit(0);
}//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        if(ServerDetails.invoker == Invoker.ADMINISTRATOR)
        {
            AdministratorPage admin_page = new AdministratorPage();
            admin_page.show();
        }
        else if(ServerDetails.invoker == Invoker.LIBRARIAN)
        {
            LibrarianPage librarian_page = new LibrarianPage();
            librarian_page.show();
        }
        else if(ServerDetails.invoker == Invoker.EMPLOYEE)
        {
            EmployeePage employee_page = new EmployeePage();
            employee_page.show();
        }
        else
            System.exit(0);
}//GEN-LAST:event_jButton2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ResultSet result_set = query_class.retrieve_book();
        try
        {
            result_set.next();
            return_date = result_set.getDate("DateOfReturn");
            jLabel3.setText(member_id);
            jLabel10.setText(reference_no);
            date_of_issue.clear();
            date_of_issue.set(result_set.getDate("DateOfIssue").getYear(), result_set.getDate("DateOfIssue").getMonth(), result_set.getDate("DateOfIssue").getDate());
            date_of_return.clear();
            date_of_return.set(result_set.getDate("DateOfReturn").getYear(), result_set.getDate("DateOfReturn").getMonth(), result_set.getDate("DateOfReturn").getDate());
            DateFormat date_format = DateFormat.getDateInstance(DateFormat.LONG);
            jLabel11.setText(date_format.format(result_set.getDate("DateOfIssue")));
            jLabel12.setText(date_format.format(result_set.getDate("DateOfReturn")));
            jLabel13.setText(String.valueOf(calculate_fine()));
            jLabel3.setSize(jLabel3.getPreferredSize());
            jLabel10.setSize(jLabel10.getPreferredSize());
            jLabel11.setSize(jLabel11.getPreferredSize());
            jLabel12.setSize(jLabel12.getPreferredSize());
            jLabel13.setSize(jLabel13.getPreferredSize());
            this.validate();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null ,"Couldn't connect to the server.\nCheck the server and restart the Application" , "Server Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowOpened

    private int calculate_fine()
    {
        int i = 0;

        Calendar now = Calendar.getInstance();
        now.setTime(new java.util.Date());

        long date_return = return_date.getTime(), date_now = now.getTimeInMillis(), diff_in_time, diff_in_days;
        diff_in_time = date_now - date_return;
        System.out.println(now);
        System.out.println(date_return);
        System.out.println(date_now);
        System.out.println(diff_in_time);
        diff_in_days = diff_in_time/(1000*60*60*24);
        System.out.println(diff_in_days);

        i = (int)(diff_in_days*2);
        if(i < 0)
            i = 0;

        return(i);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
