/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ServerDetails.java
 *
 * Created on Dec 12, 2009, 8:30:45 PM
 */

import java.io.*;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Rohit Aggarwal
 */
public class ServerDetails extends javax.swing.JFrame
{
    private int database_answer;
    public static String driver_string, dsn_url, user_name, password, driver_type, library_name, login_user, create_dsn_url;
    public static Connection server_connection;
    public static Invoker invoker;
    public static Database database;
    public static boolean window_auth;
    
    /** Creates new form ServerDetails */
    public ServerDetails()
    {
        Connectivity connectivity = new Connectivity(this, true);
        connectivity.show();
        initComponents();
        jLabel1.setSize(jLabel1.getPreferredSize());
        jLabel2.setSize(jLabel2.getPreferredSize());
        jLabel3.setSize(jLabel3.getPreferredSize());
        jLabel4.setSize(jLabel4.getPreferredSize());
        jLabel5.setSize(jLabel5.getPreferredSize());
        jLabel6.setSize(jLabel6.getPreferredSize());
        jComboBox1.setSize(jComboBox1.getPreferredSize());
        jButton1.setSize(jButton1.getPreferredSize());
        jButton2.setSize(jButton2.getPreferredSize());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel5.setText("User Name");

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel6.setText("Password");

        jTextField3.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N

        jRadioButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jRadioButton1.setText("Windows Authentication");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jRadioButton2.setText("Server Authentication");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server Details");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 24));
        jLabel1.setText("Library Management System");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 340, 29);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel2.setText("Database");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 69, 20);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel3.setText("Driver String");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 99, 20);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jLabel4.setText("URL/DNS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 160, 100, 20);

        jComboBox1.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Microsoft Access", "Microsoft SQL Server", "MySQL", "PostgreSQL" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(150, 75, 189, 26);

        jTextField1.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 115, 225, 26);

        jTextField2.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 155, 225, 26);

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 16)); // NOI18N
        jButton1.setText("Continue >>");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 200, 125, 29);

        jButton2.setFont(new java.awt.Font("Century Schoolbook", 0, 16));
        jButton2.setText("!! Cancel !!");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(225, 200, 125, 29);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-275)/2, 400, 275);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if(Connectivity.driver_type == 1)
        {
            jLabel4.setText("DNS String");
            jLabel4.setSize(jLabel4.getPreferredSize());
            driver_type = "Type 1";
            jTextField1.setText("sun.jdbc.odbc.JdbcOdbcDriver");
            jTextField1.setEditable(false);                    
		}
        else if (Connectivity.driver_type == 4)
        {
            jLabel4.setText("Server URL");
            jLabel4.setSize(jLabel4.getPreferredSize());
            driver_type = "Type 4";
            jComboBox1.removeItem("Microsoft Access");
            database_answer = JOptionPane.showOptionDialog(this, "Has the administrator created the database?", "Library", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

            if(database_answer == JOptionPane.YES_OPTION || database_answer == JOptionPane.NO_OPTION)
            {
                if(database_answer == JOptionPane.YES_OPTION)
                {
                    int database_answer_2 = JOptionPane.showOptionDialog(this, "Has the database been created with the name Library?", "Library", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

                    if(database_answer_2 == JOptionPane.NO_OPTION)
                    {
                        JOptionPane.showMessageDialog(this,"Create the database with the name Library before proceeding.","Library",JOptionPane.INFORMATION_MESSAGE);
                        System.exit(0);
                    }
                }
            }
            else
                System.exit(0);
        }        
    }//GEN-LAST:event_formWindowOpened

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(check_data() == true)
        {
            if(jComboBox1.getSelectedItem().toString().compareTo("Microsoft Access") == 0)
                database = Database.MSACCESS;
            else if(jComboBox1.getSelectedItem().toString().compareTo("Microsoft SQL Server") == 0)
                database = Database.SQLSERVER;
            else if(jComboBox1.getSelectedItem().toString().compareTo("MySQL") == 0)
                database = Database.MYSQL;
            else if(jComboBox1.getSelectedItem().toString().compareTo("PostgreSQL") == 0)
                database = Database.POSTGRESQL;
            driver_string = jTextField1.getText();
            dsn_url = jTextField2.getText();
            if(driver_type.compareTo("Type 4") == 0)
            {
                user_name = jTextField3.getText();
                password = jPasswordField1.getText();
            }
            else
            {
                user_name = null;
                password = null;
            }            

            try
            {
                File server_file = new File("C:\\Server File.lms");
                server_file.createNewFile();
                FileWriter write_file = new FileWriter(server_file);
                BufferedWriter write_server_file = new BufferedWriter(write_file);
                write_server_file.write(database.getName());
                write_server_file.newLine();
                write_server_file.write(driver_type);
                write_server_file.newLine();
                write_server_file.write(driver_string);
                write_server_file.newLine();

                if(Connectivity.driver_type == 4 && database_answer == JOptionPane.NO_OPTION && database.getName().equals(database.SQLSERVER.toString()))
                {
                    write_server_file.write(dsn_url + ";databaseName=Library");
                    create_dsn_url = dsn_url;
                    dsn_url += ";databaseName=Library";
                }
                else if(Connectivity.driver_type == 4 && database_answer == JOptionPane.NO_OPTION)
                {
                    write_server_file.write(dsn_url + "/Library");
                    create_dsn_url = dsn_url;
                    dsn_url += "/Library";
                }
                else
                    write_server_file.write(dsn_url);

                write_server_file.newLine();
                if(window_auth == true)
                    write_server_file.write("true");
                else
                    write_server_file.write("false");
                write_server_file.newLine();
                write_server_file.write(user_name);
                write_server_file.newLine();
                write_server_file.write(password);
                write_server_file.close();
                write_file.close();
                this.dispose();

                if(driver_type.compareTo("Type 1") == 0)
                    new ConnectServerType1();

                else if(driver_type.compareTo("Type 4") == 0 && database_answer == JOptionPane.NO_OPTION)
                {
                    switch(jComboBox1.getSelectedIndex())
                    {
                        case 0: new CreateMSSQLDatabase();
                            break;
                        case 1: new CreateMySQLDatabase();
                            break;
                        case 2: new CreatePostgreSQLDatabase();
                            break;
                        default : JOptionPane.showMessageDialog(this, "Database can't be created.\nContact the Database Administrator.", "Database Error", JOptionPane.ERROR_MESSAGE);
                            server_file.delete();
                            break;
                    }
                }

                else if(driver_type.compareTo("Type 4") == 0)
                    new ConnectServerType4();
            }

            catch(IOException e)
            {
                JOptionPane.showMessageDialog(this, "Server File can't be created.\nRestart the application and try again.", "Server File", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }

        else
            JOptionPane.showMessageDialog(this, "Correct the highlighted items before proceeding", "Incorrect Data", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(driver_type.compareTo("Type 4") == 0)
        {
            if(jComboBox1.getSelectedItem().toString().compareTo(Database.MYSQL.toString()) == 0 ||
               jComboBox1.getSelectedItem().toString().compareTo(Database.POSTGRESQL.toString()) == 0)
            {
                jRadioButton1.setSelected(false);
                jRadioButton2.setSelected(false);
                this.remove(jRadioButton1);
                this.remove(jRadioButton2);
                jLabel5.setBounds(20, 200, jLabel5.getPreferredSize().width, jLabel5.getPreferredSize().height);
                this.add(jLabel5);
                jLabel6.setBounds(20, 240, jLabel6.getPreferredSize().width, jLabel6.getPreferredSize().height);
                this.add(jLabel6);
                jTextField3.setBounds(150, 195, 225, 26);
                this.add(jTextField3);
                jPasswordField1.setBounds(150, 235, 225, 26);
                this.add(jPasswordField1);
                jButton1.setBounds(40, 295, jButton1.getPreferredSize().width, jButton1.getPreferredSize().height);
                jButton2.setBounds(225, 295, jButton2.getPreferredSize().width, jButton2.getPreferredSize().height);
                java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
                setBounds((screenSize.width-400)/2, (screenSize.height-375)/2, 400, 375);
                this.validate();
            }
            else if(jComboBox1.getSelectedItem().toString().compareTo(Database.SQLSERVER.toString()) == 0)
            {
                if(System.getProperty("os.name").contains("Windows") == true)
                {
                    this.remove(jLabel5);
                    this.remove(jLabel6);
                    this.remove(jTextField3);
                    this.remove(jPasswordField1);
                    jRadioButton1.setBounds(75, 200, jRadioButton1.getPreferredSize().width, jRadioButton1.getPreferredSize().height);
                    this.add(jRadioButton1);
                    jRadioButton2.setBounds(75, 230, jRadioButton2.getPreferredSize().width, jRadioButton2.getPreferredSize().height);
                    this.add(jRadioButton2);
                    jButton1.setBounds(40, 275, jButton1.getPreferredSize().width, jButton1.getPreferredSize().height);
                    jButton2.setBounds(225, 275, jButton2.getPreferredSize().width, jButton2.getPreferredSize().height);
                    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
                    setBounds((screenSize.width-400)/2, (screenSize.height-350)/2, 400, 350);
                    this.validate();
                }
                else
                {
                    this.remove(jRadioButton1);
                    this.remove(jRadioButton2);
                    jLabel5.setBounds(20, 200, jLabel5.getPreferredSize().width, jLabel5.getPreferredSize().height);
                    this.add(jLabel5);
                    jLabel6.setBounds(20, 240, jLabel6.getPreferredSize().width, jLabel6.getPreferredSize().height);
                    this.add(jLabel6);
                    jTextField3.setBounds(150, 195, 200, 26);
                    this.add(jTextField3);
                    jPasswordField1.setBounds(150, 235, 200, 26);
                    this.add(jPasswordField1);
                    jButton1.setBounds(40, 295, jButton1.getPreferredSize().width, jButton1.getPreferredSize().height);
                    jButton2.setBounds(225, 295, jButton2.getPreferredSize().width, jButton2.getPreferredSize().height);
                    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
                    setBounds((screenSize.width-400)/2, (screenSize.height-375)/2, 400, 375);
                    this.validate();
                }
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
        jRadioButton1.setSelected(true);
        if(jRadioButton1.isSelected() == true)
        {
            window_auth = true;
            this.remove(jLabel5);
            this.remove(jLabel6);
            this.remove(jTextField3);
            this.remove(jPasswordField1);
            jButton1.setBounds(40, 275, jButton1.getPreferredSize().width, jButton1.getPreferredSize().height);
            jButton2.setBounds(225, 275, jButton2.getPreferredSize().width, jButton2.getPreferredSize().height);
            java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            setBounds((screenSize.width-400)/2, (screenSize.height-350)/2, 400, 350);
            this.validate();
        }                              
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(true);
        if(jRadioButton2.isSelected() == true)
        {
            window_auth = false;
            jLabel5.setBounds(20, 270, jLabel5.getPreferredSize().width, jLabel5.getPreferredSize().height);
            this.add(jLabel5);
            jLabel6.setBounds(20, 310, jLabel6.getPreferredSize().width, jLabel6.getPreferredSize().height);
            this.add(jLabel6);
            jTextField3.setBounds(150, 265, 200, 26);
            this.add(jTextField3);
            jPasswordField1.setBounds(150, 305, 200, 26);
            this.add(jPasswordField1);
            jButton1.setBounds(40, 350, jButton1.getPreferredSize().width, jButton1.getPreferredSize().height);
            jButton2.setBounds(225, 350, jButton2.getPreferredSize().width, jButton2.getPreferredSize().height);
            java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
            setBounds((screenSize.width-400)/2, (screenSize.height-425)/2, 400, 425);
            this.validate();
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private boolean check_data()
    {
        boolean return_value = true;

        if(jTextField1.getText() == null || jTextField1.getText().compareTo("") == 0)
        {
            jLabel3.setText("<html><font color='red'>Driver String");
            return_value = false;
        }
        else
            jLabel3.setText("Driver String");

        if(jTextField2.getText() == null || jTextField2.getText().compareTo("") == 0)
        {
            if(Connectivity.driver_type == 1)
                jLabel4.setText("<html><font color='red'>DNS String");
            else if(Connectivity.driver_type == 4)
                jLabel4.setText("<html><font color='red'>Server URL");
            return_value = false;
        }
        else
        {
            if(Connectivity.driver_type == 1)
                jLabel4.setText("DNS String");
            else if(Connectivity.driver_type == 4)
                jLabel4.setText("Server URL");
        }

        if(driver_type.compareTo("Type 4") == 0)
        {
            if(jComboBox1.getSelectedItem().toString().compareTo(Database.SQLSERVER.toString()) == 0)
            {
                if(jRadioButton1.isSelected() == false && jRadioButton2.isSelected() == false)
                {
                    return_value = false;
                }
                else if(jRadioButton2.isSelected())
                {
                    if(jTextField3.getText() == null || jTextField3.getText().isEmpty())
                    {
                        jLabel5.setText("<html><font color='red'>User Name");
                        jLabel5.setSize(jLabel5.getPreferredSize());
                        return_value = false;
                    }
                    else
                    {
                        jLabel5.setText("User Name");
                        jLabel5.setSize(jLabel5.getPreferredSize());
                    }

                    if(jPasswordField1.getText() == null || jPasswordField1.getText().isEmpty())
                    {
                        jLabel6.setText("<html><font color='red'>Password");
                        jLabel6.setSize(jLabel6.getPreferredSize());
                        return_value = false;
                    }
                    else
                    {
                        jLabel6.setText("Password");
                        jLabel6.setSize(jLabel6.getPreferredSize());
                    }
                }
            }
            else
            {
                if(jComboBox1.getSelectedItem().toString().compareTo(Database.MYSQL.toString()) == 0 ||
                    jComboBox1.getSelectedItem().toString().compareTo(Database.POSTGRESQL.toString()) == 0)
                {
                    if(jTextField3.getText() == null || jTextField3.getText().isEmpty())
                    {
                        jLabel5.setText("<html><font color='red'>User Name");
                        jLabel5.setSize(jLabel5.getPreferredSize());
                        return_value = false;
                    }
                    else
                    {
                        jLabel5.setText("User Name");
                        jLabel5.setSize(jLabel5.getPreferredSize());
                    }

                    if(jPasswordField1.getText() == null || jPasswordField1.getText().isEmpty())
                    {
                        jLabel6.setText("<html><font color='red'>Password");
                        jLabel6.setSize(jLabel6.getPreferredSize());
                        return_value = false;
                    }
                    else
                    {
                        jLabel6.setText("Password");
                        jLabel6.setSize(jLabel6.getPreferredSize());
                    }
                }
            }
        }

        return(return_value);
    }  

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
